version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19Agustus
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:19Agustus@db/todo_db
    working_dir: /app
    volumes:
      - .:/app
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build: ./frontend
    container_name: todo-app-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]
    depends_on:
      - app

volumes:
  postgres_data:
